// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dernjnznyhvqvlywpvug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlcm5qbnpueWh2cXZseXdwdnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MzUwMzcsImV4cCI6MjA2ODIxMTAzN30.r-wRxw4SpdihT2JGmZFJlin6JRvvSfhNzvLDg7C1GvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});